### ISSUE TITLE
[FR] Move DNSSEC add-on (custom-pages) to the proper location (inside modules/addons)

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#194]
**Is your feature request related to a problem? Please describe.**
-
We don't feel that it is a good practice to put folders in the root of WHMCS installation.
According to the [Openprovider-WHMCS-domains documentation](https://github.com/openprovider/Openprovider-WHMCS-domains#allow-end-users-to-edit-dnssec-records) we are supposed to place the folder `custom-pages` at the root of the WHMCS installation. We don't agree with this method and believe it should be improved.

**Describe the solution you'd like**
-
There is a folder for such kinds of addons. The correct path is: `{whmcs_root}/modules/addons/` - we vote for this folder to be placed there. It could even be inside the already existing `openprovider` folder which actually would be the better option.

**Describe alternatives you've considered**
-
...

**Additional context**
-
...

Thank you.

**Comment by wmetge** [comment]
@maverick85 thank you for feedback, we will add it to our list of priorities for the next release of the module

**Comment by sapillai** [comment]
Hi @maverick85,

Sorry for not getting back to you sooner on this.

The module currently uses a method [publicly documented by WHMCS](https://developers.whmcs.com/advanced/creating-pages/) for DNSSEC page and as per WHMCS documentation, _"Custom pages created in this way should always be located in the root WHMCS directory. Attempting to use this code outside of the root directory is unsupported"_. Hence unfortuntely, it is not possible to change the location of the file with the current method. As an improvement, we have automated copying of the file in the latest version of the [module](https://github.com/openprovider/Openprovider-WHMCS-domains/archive/refs/tags/v5.8.0.zip).   

We are currently reviewing the possibility of moving DNSSEC page and language file to addons folder as  you suggested. A task has already been created for our developers and this is currently in progress. We plan to include this change in the next release.

**Comment by maverick85** [comment]
Dear @sapillai 

I am sorry but it seems to me that you have misread the documentation.

Please allow me to point to the relevant topic:

> **Creating your own client area pages should ordinarily be done by creating an Addon Module with client area output.**
>
> However, if you wish to, you can create a standalone page using the following template.

Allow me to repeat:
> **Creating your own client area pages should ordinarily be done by creating an Addon Module with client area output.**

It is literally the first line on the page you mention.
And please, be advised:
> _Custom pages created in this way should always be located in the root WHMCS directory. Attempting to use this code outside of the root directory is unsupported._

Created ... THIS WAY
You chose to create the page ... THIS WAY.

THIS WAY is not the recommended way. It is POSSIBLE, it is not the proper procedure.
The proper way is:
> **Creating your own client area pages should ordinarily be done by creating an Addon Module with client area output.**

I appreciate your feedback, but ... reveals some issues on your analysis.

**Comment by sapillai** [comment]
Dear @maverick85,

It seems like there might have been a misunderstanding of my comment.

To clarify, I just shared the method currently used in the module and the fact that it does not allow moving the file outside of the root directory. It looks like you might have missed the important part of my reply where I said that **current approach will be reviewed and a task is already in-progress**:

>**_We are currently reviewing the possibility of moving DNSSEC page and language file to addons folder as you suggested. A task has already been created for our developers and this is currently in progress. We plan to include this change in the next release._**

**Comment by maverick85** [comment]
Clearly YES, there is a communication problem.
I imagine the communication problem stems from the fact that months and years go by without any resolution of the mentioned issues, then you make a comment like:

> Hence unfortuntely, it is not possible to change the location of the file with the current method. As an improvement, we have automated copying of the file in the latest version of the [module](https://github.com/openprovider/Openprovider-WHMCS-domains/archive/refs/tags/v5.8.0.zip).

It is not possible with the current method, adds nothing of interest to the conversation. Interesting would be "we're planning to start working on the proper method for the next release before the EOY".
Now just imagine you had dedicated the time of making an automated method to copy the file, you had actually been working on taking the correct approach?

Working with OpenProvider and OpenProvider modules is the slowest and one of the worse experience possible. Any resolution takes years. It'll be years until stuff like this gets fixed. Because the task in progress to an issue opened in **October 28, _2021_** is a comment on **June 20, _2024_** (2 and a half years later) with nothing to show. NOTHING. But this is not a you (@sapillai) problem. This is a very serious management problem, that has been perspiring to your customers for years.

> Automated copying of the file (...)
That must have been some solid and challenging work.

**Comment by sapillai** [comment]
Hi @maverick85,

I apologize if my comment on June 20 was unclear. I wanted to explain why a direct file move isn't possible with the current method and that we started reviewing your suggestion about moving DNSSEC to an addon. Because I think it's important to keep our customers informed about the status of their feature requests.

> THIS WAY is not the recommended way. It is POSSIBLE, it is not the proper procedure.

I would like to clarify that we have discussed our current method with WHMCS ([www.whmcs.com](http://www.whmcs.com/)), and their head of support has confirmed that the method used in our module is a recommended option and there are no security issues associated with it. I am adding his comment below for reference: 

"_**The steps at https://developers.whmcs.com/advanced/creating-pages/ are documented and supported. This is the recommended method to create custom pages using the WHMCS theme system. There are no known security issues with this method.**_"

Despite this, we tested your suggested approach internally. However, using the addon method would result in the DNSSEC page becoming standalone, meaning that other domain management options currently available on the sidebar in client area would not be accessible when on the new DNSSEC page. Additionally, customers would need to ensure that the addon is installed and updated every time there is a change to allow DNSSEC management for end customers. Therefore, we do not see any advantage in moving to the addon method.

We appreciate your input and will continue to explore ways to improve our module and service. Thank you for your understanding.
