### ISSUE TITLE
[BUG] Invalid telephone country code!

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#219]
When updating WHOIS details, if "United Kingdom" is entered into the Country field, the customer sees "An issue was encountered while updating the domain contact details. Please contact support."

I had to enable module debugging to get the actual error:

`{"code":131,"message":"Invalid telephone country code!","total":0,"data":[]}`

If the field is left as "GB" then it works fine.

**Comment by wmetge** [comment]
Hi @willdashwood , thanks for bringing this up. We'll get to it as soon as possible

**Comment by sapillai** [comment]
Hi @willdashwood,

We have added an improvement for this in the latest [release](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0). Now the module log will contain a knowledgebase article link with supported country codes so that you can easily find out and advise your clients which country code to use.
 
![image](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/97894083/5fbc2459-bb64-468f-bfde-c8623f6ff629)

I hope it helps!
