### ISSUE TITLE
[BUG] Empty authorization code!

### ISSUE THREAD

**Issue by Raboo** [openprovider/Openprovider-WHMCS-domains#229]
**Describe the bug**
When transferring a domain automation fails because of `Empty authorization code!`

**To Reproduce**
Client enters their EPP code during the order process and yet this plugin fails cause of `Empty authorization code!` even if the client has entered the EPP/Auth code.

**Expected behavior**
It should work with and without whitespace in the zip code.

**Screenshots**

```
An order has received its first payment but the automatic provisioning has failed and requires you to manually check & resolve.

Client ID: 1
Domain ID: 32
Registration Type: Transfer
Domain: domain.nu
Error: Empty authorization code!
```

**Server info:**
 - Distro: Ubuntu
 - PHP: v.7.2
 - Web server: [e.g. httpd, nginx] nginx + httpd
 - WHMCS: 8.4
 - Plugin: v5.6

**Comment by wmetge** [comment]
@Raboo Do I understand correctly that this occurs when the client has entered an EPP code, but the zip code is invalid as described in #229?

are you able to see the EPP code from the domain details page in the admin area of WHMCS?

**Comment by Raboo** [comment]
I still get this problem after I formatted the zip code correctly for the client.

**Comment by sapillai** [comment]
Hi @Raboo,

I'm in the process of reviewing all outstanding GitHub issues and feature requests.

I tried to test a .nu transfer via the Openprovider WHMCS module, but I was unable to recreate the problem. Our logs indicate that all .nu transfer requests (from different resellers) from the Openprovider WHMCS module in the last 6 months had auth code included. 

I request you to try .nu transfers using the latest version of the [module](https://github.com/openprovider/Openprovider-WHMCS-domains/archive/refs/tags/v5.8.0.zip) and if you experience any issues, please contact our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with following details so that we can investigate it:

- Reseller ID
- [module logs](https://docs.whmcs.com/Troubleshooting_Module_Problems)
- WHMCS, Openprovider module and PHP version details
