### ISSUE TITLE
[BUG]The cron for downloading the TLD prices was not run yet

### ISSUE THREAD

**Issue by ghost** [openprovider/Openprovider-WHMCS-domains#238]
Select: TLD Import & Pricing Sync,
Select: Openprovider

Error: The cron for downloading the TLD prices was not run yet. You can run the prices download manually here. If this fails, it is likely that your WHMCS installation does not support a long execution time. [Check the manual to run the cron command instead](https://github.com/openprovider/OP-WHMCS7/blob/master/docs/TLD_Pricing_sync_Utility.md).

At Plesk: Task "/cp/modules/registrars/openprovider/cron/DownloadTldPrices.php" successfully completed in 26 seconds.

**Comment by sapillai** [comment]
Hi,

Thank you for posting the problem!

I tried running **TLD Import & Pricing Sync** in my WHMCS test environment and I can confirm that the module function and API calls are working fine.

Details of my test environment
```
WHMCS version: 8.5.1
Openprovider module version: 5.6
PHP Version: 7.4.30
PHP Memory Limit: 512MB
```
 
Due to the number of TLDs supported by Openprovider, some WHMCS installations may have time-outs when synchronizing the TLD pricing. Loading the TLD prices still requires some time to process after running this command. WHMCS requires a significant amount of time to process all TLDs. The speed depends on how fast your server is as well as your browser. In order to resolve the problem, I would suggest,
 
- Running the script a few more times when there are no other WHMCS tasks/cron jobs running.
- Increase the amount of PHP memory allocated for running scripts (memory_limit=256M or higher).
 
If you have SSH access, you can try running the script manually as follows:

1. Log in to your server via SSH.
2. Navigate to the folder 'modules/registrars/openprovider/cron'
3. Execute the following command:

`php -d error_log='' -d max_execution_time=0 -d memory_limit=256M DownloadTldPrices.php`
 
If you don't have SSH/terminal access to the server, please try adding a cron job like,
 
`15 0 * * * php -d max_execution_time=0 -d memory_limit=256M /PATH_TO_WHMCS/modules/registrars/openprovider/cron/DownloadTldPrices.php`
 
**Note**: The above cron will run at 12:15 AM at night, please adjust the time if required. Once the cron has been executed, please ensure to remove the cron task since it is a memory-intensive task for your WHMCS server.
 
Kindly update the thread if you encounter any problems.
