### ISSUE TITLE
[BUG] Plesk Webspace order

### ISSUE THREAD

**Issue by DAThosting** [openprovider/Openprovider-WHMCS-domains#243]
**Describe the bug**
If you use plesk as webspace provider you have two problems.
1. If you order a webspace with domain registration, the reg will not be performed.
2. If you want to use a existing domain the error "Something was wrong! Check your credentials and try again" occurs.

**To Reproduce**
1. Add a webhosting product with plesk
2. Try ordering that product via userinterface
3. Module Log shows, that the module tries to login with username "wssmall" which is my service plan name from plesk.

**Server info:**
WHMCS 8.5.1

**Image**
![image](https://user-images.githubusercontent.com/16845703/180778397-83b72147-323e-4cb0-b5ba-620692eb819c.png)
![image](https://user-images.githubusercontent.com/16845703/180778489-41e47ea7-b755-475a-8299-068431c1c91a.png)

**Comment by MrKoopie** [comment]
I'm unable to reproduce this with version [5.6.2](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/5.6.2). How have you configured the domain lookup, did you update the lookup provider in WHMCS admin -> domain pricing?

**Comment by sapillai** [comment]
Hi @DAThosting,

If you are still experiencing this problem, please contact our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with following details so that we can investigate it:


- [module logs](https://docs.whmcs.com/Troubleshooting_Module_Problems)
- WHMCS, Openprovider module and PHP version details.
