### ISSUE TITLE
[Bug] Domain Search Is Resulting Error 500

### ISSUE THREAD

**Issue by pmjcreations** [openprovider/Openprovider-WHMCS-domains#255]
**Describe the bug**
When WHMC Name Spinning is used as Lookup Provider, a 500 error happens. It works fine when using Domain Registrar > Openprovider.

**To Reproduce**
1. Go to Lookup Provider in WHMCS Admin and use WHMC Name Spinning and Save.
2. Now, go to the cart page and search for any domain name. 
3. I'm getting 500 status
4. Switch to Domain Registrar > Openprovider from the Lookup Provider page.
5. Now, search for any domain name on the cart page, and it will show the results. 

**Expected behavior**
The domain search results should be working regardless of the Lookup Provider.

**Server info:**
 - Distro: CloudLinux
 - PHP: 7.4 and 8.1
 - Web server: Nginx + Apache

**Comment by maverick85** [comment]
Sorry to barge in but just wondering, so if the Openprovider module works without error, and when it's not invoked the error shows, shouldn't this be reported somewhere else?

**Comment by sapillai** [comment]
Hi @pmjcreations,

WHMCS Namespinning is the default lookup provider included with the platform, so any problems with it should be reported to WHMCS support. 

You might want to try enabling the display errors feature before contacting WHMCS support, since you are getting 500 errors. Please refer to following WHMCS documentations. 
https://docs.whmcs.com/Troubleshooting_Guide#500_Internal_Server_Error
https://docs.whmcs.com/PHP_and_WHMCS
