### ISSUE TITLE
[BUG] Registrar TLD Sync + PHP8

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#262]
**Describe the bug**
This is another PHP8 compatibility error following up on the following issues:
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/252
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/258

The Domain TLD Sync script cannot be ran as it fails with errors.

**To Reproduce**
Have WHMCS on PHP8
Run the cron script.

**Expected behavior**
Successful conclusion.

**Server info:**
 - Distro: AlmaLinux 9
 - PHP: 8.1
 - Web server: httpd

Error:
```
# php -d max_execution_time=0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php
[WHMCS Application] ERROR: TypeError: array_merge():
 Argument #1 must be of type array, null given in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php:344
  Stack trace:
   #0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php(344): array_merge()
   #1 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php(13): openprovider_registrar_launch_decorator()
   #2 {main} {"exception":"[object] (TypeError(code: 0): array_merge():
    Argument #1 must be of type array, null given at /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php:344)"} []
TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php:344

#0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php(344): array_merge()
#1 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php(13): openprovider_registrar_launch_decorator()
#2 {main}
```

**Comment by sapillai** [comment]
@maverick85 

Sorry for the inconvenience caused. 

We are aware of the issue and a fix has already been prepared. We will publish the fix in the next few days after it has been reviewed and tested extensively. For now, in order to resolve the issue, please make the following change manually. 

Comment out line 344 in file modules/registrars/openprovider/openprovider.php
`//    $modifiedParams['original'] = array_merge($params['original'], Configuration::getParams());`


And replace it with the following code:
```
 if (isset($params['original'])) { 
    $modifiedParams['original'] = array_merge($params['original'], Configuration::getParams()); 
} else { 
    $modifiedParams['original'] = Configuration::getParams(); 
       }   
``` 

We have tested the fix with PHP 8.1 and the script successfully imported domain prices using `searchExtensionRequest`.

If you need further assistance, please reach out to [Openprovider Support team](https://www.openprovider.com/company/contact-us/contact-support).
