### ISSUE TITLE
[BUG] Wrong prices when sync with WHMCS

### ISSUE THREAD

**Issue by Remarkable-Guille** [openprovider/Openprovider-WHMCS-domains#267]
**Describe the bug**
Wrong price when syncing prices with the WHMCS native method

**To Reproduce**
1. Go to "Domain Pricing."
2. Click on "Click here to Sync Now."
3. Select OpenProvider
4. Set "Margin Type to Percentage or Fixed Amount."
5. Set "Profit Margin to 0"
6. Set Round to Next to "No Rounding"
7. Select a tld. example  ".com"
8. Click on "Import x TLD"
9. Check .com prices again

**Expected behavior**
.com price should be $9.15, not $8.57

**Server info:**
 - Distro: Almalinux/Cloudlinux 8
 - PHP: 8.1
 - Web server: Litespeed
 - WHMCS 8.6.1
 - Openprovider WHMCS Module: Lastest master branch

**Additional context**

**Comment by sapillai** [comment]
@Remarkable-Guille 

It appears that you are seeing cached prices. The module fetches TLD prices using the [DownloadTldPrices.php](https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/modules/registrars/openprovider/cron/DownloadTldPrices.php) script. In order to get latest prices, you will need to run the [DownloadTldPrices.php](https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/modules/registrars/openprovider/cron/DownloadTldPrices.php) script. 

![image](https://user-images.githubusercontent.com/97894083/224256684-09d3fd1f-4650-46f4-af51-36c64a40bbdd.png)

If you want to regularly cache the price changes, you will need to configure a cron job to run the [DownloadTldPrices.php](https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/modules/registrars/openprovider/cron/DownloadTldPrices.php) script. I would suggest scheduling the cron to run at off-peak hours since it is a memory intensive task.

Please refer to https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/docs/TLD_Pricing_sync_Utility.md for instructions.
