### ISSUE TITLE
WHMCS OpenProvider new own module

### ISSUE THREAD

**Issue by maxihoster** [openprovider/Openprovider-WHMCS-domains#280]
I inform you I will release this week or beggining of next week a full new module with all the fix for OpenProvider Domains registrars.
If you are interested about this new module. don't hesitate to contact me.

**Comment by saulmayo** [comment]
> I inform you I will release this week or beggining of next week a full new module with all the fix for OpenProvider Domains registrars. If you are interested about this new module. don't hesitate to contact me.

Did you finally get the module to work correctly? Are you going to publish it or what are your intentions?

**Comment by crossfirehost** [comment]
I would be interested.

Openprovider has officially given up on this plugin, as per the top of the README on the repository.

If anyone has alternative options for a registrar as cheap as OP that integrates better with WHMCS feel free to recommend.

**Comment by Pixcale** [comment]
@maxihoster Any update on this?

**Comment by willdashwood** [comment]
We would certainly be interested too. Are you planning on forking this code and publishing on github? We're not desperate to upgrade to PHP 8+ at present but obviously at some point we will. I'm happy to contribute to development.

**Comment by NTaravati** [comment]
Please drop me a line.

**Comment by lennarttd** [comment]
Also interested.

**Comment by anetadocrego** [comment]
Also interested!

**Comment by maxihoster** [comment]
Sorry I was totally busy! I will contact the dev today and let you know the status. Because me I have leave WHMCS for using HostBill! But I have already paid the dev and I have stop the process. I will let you know

**Comment by maxihoster** [comment]
Hello! The new module is finally ready for WHMCS / OpenProvider!

I have paid the company www.whmcsglobalservices.com for developping this module!

Because I don't have anymore WHMCS I can't test it for you!

You can buy the module directly to WHMCS Global Services ! It will be sell at a very excellent pricing!

**Comment by Pixcale** [comment]
@sapillai @wmetge @Batekk @dinusharath @MrKoopie

Any update guys!?

**Comment by Remarkable-Guille** [comment]
For me, this is a very weird business move; instead of hiring competent in-house developers or hiring a third-party dev, they decided to drop the support for the module; my concern is that the Openprovider business model is focused on resellers, and a good chunk of resellers use WHMCS, it makes me wonder is the company is running smoothly, and they are still fully committed to their resellers.

I have contacted whmcsglobalservices.com; they don't have the modules on their website, but when asked in the chat, they quoted me $129 /year or $249 lifetime (or something like that) no too bad, but when you resale domains, any cent counts

**Comment by willdashwood** [comment]
@sapillai contacted me by email regarding a different bug I posted ages ago. When I said I thought OpenProvider had abandoned development on the WHMCS module he replied:

"Development of the module is currently paused as our last attempts to fix bugs didn't go as we planned. We now have new developers for our WHMCS modules, and they are reviewing pending bugs in domain module and trying to fix issues. Once outstanding issues are resolved, we will focus on improving the module."

I really think OpenProvider should put out a statement to everyone because I'm sure people are thinking of leaving or have already left based on the perception that WHMCS has abandoned this module.

**Comment by pmjcreations** [comment]
Hi @willdashwood,

Thank you so much for letting us know  ❤️

**Comment by Pixcale** [comment]
Yesterday another email arrived from OpenProvider with the subject "WHMCS module update is coming at the end of Q1".

This made my day! Thanks

**Comment by pmjcreations** [comment]
Weew @Pixcale. Thanks for letting us know.

I would like to see if they are working on PHP 8.2 or lower; as I  mentioned, WHMCS will release PHP 8.2 support in the first half of 2024. So, we don't need to start the same struggle to get this module to work with PHP 8.2 or higher

**Comment by pmjcreations** [comment]
Hi @sapillai, https://github.com/openprovider/Openprovider-WHMCS-domains/tree/version-8?tab=readme-ov-file#domain-module-for-whmcs-8x says WHMCS 8.8.0. As of now, the latest major version is  v8.9

**Comment by sapillai** [comment]
@pmjcreations yes, we are aware that WHMCS 8.9.0 is currently in General Availability and we already testing all the changes, fixes on the new WHMCS version as well.

**Comment by sapillai** [comment]
A beta version of the new Openprovider module with PHP 8.1 bug fixes and compatible with WHMCS 8.9 is available for testing. If you would like to participate in beta testing, please [contact our support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) or your account manager.
