### ISSUE TITLE
[BUG] Something went wrong and we couldn't process your request.

### ISSUE THREAD

**Issue by musakhalid** [openprovider/Openprovider-WHMCS-domains#322]
**Describe the bug**

Once we activate your module, we got this error on invoice page while customer trying to make payment, and once the openprovider folder is deleted everything works fine! The server is powered by PHP 8.1

Fatal error: Cannot redeclare getadminpermsarray() in unknown on line 0
Oops!
Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

Whoops\Exception\ErrorException: Cannot redeclare getadminpermsarray() in unknown:0
Stack trace:
#0 /home/*******/public_html/******
![Screenshot 2024-07-11 at 12-32-39 Oops!](https://github.com/openprovider/Openprovider-WHMCS-domains/assets/32104619/1f9eed00-6cd4-47c1-b5b8-c7b65e996cad)
/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(1, 'Cannot redeclar...', 'unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Server info:**
 - Distro: 
 - PHP: 8.1
 - Web server: LiteSpeed Powered

**Comment by sapillai** [comment]
Hi @musakhalid,

Thank you for reporting the issue.

The function that's being declared twice `getadminpermsarray` is not part of the stock WHMCS installation and on a quick check, I don't see any reference of this function in our module code. 

We tried to reproduce the problem on our WHMCS instances with PHP 8.1 and module version 5.8.0, but we couldn't. Could you please open a [support ticket](https://www.openprovider.com/company/contact-us/contact-support) and provide following details so that we can check this further?

* Reseller ID
* Module logs (enable module log and reproduce the issue). You can find instructions to enable module logs at https://docs.whmcs.com/troubleshooting/logs-in-whmcs/#module-log
* Are you able to reproduce the problem as admin?
* Contents of your modules directory

**Comment by sapillai** [comment]
Hi @musakhalid,

Our module developers checked the module code and they couldn't find any place where we use this function - getadminpermsarray(). Based on the information from developers, the function returns the list of permissions that you see when [creating or editing a role](https://docs.whmcs.com/admins/admin-tutorials/add-or-edit-an-administrator-role/) 

Example output
```
Array
(
    [1] => Main Homepage
    [3] => My Account
    [4] => List Clients
    [152] => List Users
    [153] => Delete Users
    ................
    ................
```

If you can open a [support ticket](https://www.openprovider.com/company/contact-us/contact-support) and provide details mentioned in my last comment, we will be happy to check further to see why it occurs when activating the Openprovider module.
