### ISSUE TITLE
[FR] Open the NewDnsManagerFeature in new tab

### ISSUE THREAD

**Issue by Gerbildral** [openprovider/Openprovider-WHMCS-domains#340]
when the page opens in a new tab it would be more user friendly because now you get redirected to a different site.

**Comment by sapillai** [comment]
Hi @Gerbildral,

Thank you for posting.

Sorry, I am unable to understand the feature request. The DNS Management option in WHMCS client area won't redirect you to a different site. Can you please provide some more details?

1. Version of Openprovider WHMCS module you are using. You should be able to check module version from **WHMCS Admin Dashboard >> Configuration >> System Settings >> Domain Registrars >>** Click on '**Configure**' button for Openprovider module.
2. Steps of how you are managing DNS of domains from WHMCS? Please include a screenshot if possible (please hide any sensitive information).

I look forward to hearing back from you.

**Comment by Gerbildral** [comment]
Hi @sapillai 

In the advanced-module-configurations.php file you have the option for "useNewDnsManagerFeature"
if it is false you use the build-in DNS manager of WHMCS. When you enable it you use [Single Domain DNS panel](https://support.openprovider.eu/hc/en-us/articles/360014539999-Single-Domain-DNS-panel) from OP. when you use that panel you get redirected to a site called dnspanel.io but instead of opening it in the same tab it could be nicer if it would open in a new tab.

I'm running the latest version v5.8.0-REST

**Comment by sapillai** [comment]
Hi @Gerbildral,

Thank you for providing more details about your feature request. I initially tested the native WHMCS DNS manager since the default setting for 'useNewDnsManagerFeature' is false.

I believe this feature can be implemented. I will discuss it with our development team and will update you by tomorrow.

**Comment by sapillai** [comment]
Hi @Gerbildral,

Thank you for waiting!

We will add this feature to the Openprovider domain registrar module so that end-users/domain owners can still remain in WHMCS client area, view and navigate to other domain management options. A task has been created for our development team to make the change.

Thank you for submitting the feature request!

**Comment by sapillai** [comment]
Hi @Gerbildral,

I am glad to inform you that your feature request has been added in the latest version of our module. Beta release of the new version is available for download [under **Releases**](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.9.0-beta).
