### ISSUE TITLE
[BUG] WHMCS local API DomainGetNameservers returns an empty array

### ISSUE THREAD

**Issue by simonklink** [openprovider/Openprovider-WHMCS-domains#343]
No nameserver records are returned using the WHMCS internal API DomainGetNameservers call.
You can reproduce this by executing the DomainGetNameservers API call: 
https://developers.whmcs.com/api-reference/domaingetnameservers/

This should return the nameservers that are configured for the domain at OpenProvider.
`{
    "result": "success",
    "ns1": "ns1.example.com",
    "ns2": "ns1.example.com"
}`
The call is routed to the NameserverController get method:
`'getNameservers'     => 'NameserverController@get',`

However this return a hardcoded empty array:
https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/modules/registrars/openprovider/Controllers/System/NameserverController.php#L50

**Comment by sapillai** [comment]
Hi @simonklink,

Thank you for posting.

Can you please share following details?

- WHMCS version
- Openprovider domain registrar module version
- Are you testing in Sandbox/test mode?

**Comment by simonklink** [comment]
Hi @sapillai,

The module itself does not use this, but we do use the WHMCS localApi DomainGetNameservers call.

We have domains at several registrars and this call allows us to retrieve the domain nameservers with one call independent of where the domain is registered.

This was working in version 3.3, see the following code:
https://github.com/openprovider/Openprovider-WHMCS-domains/blob/v3.3.1/modules/registrars/openprovider/Controllers/System/NameserverController.php#L41

But with the latest version we get an empty array.
This does not allow us to determine whether the OpenProvider domains are using our nameservers or custom nameserver records.

**Comment by sapillai** [comment]
Hi @simonklink,

Thank you for providing details.

I can see that this was removed in version [3.3.3](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/3.3.3) (Apr 2, 2021) with the following comment.

![image](https://github.com/user-attachments/assets/f8f1febf-c95e-4364-a4dd-447405c38943)

I will check with our developers to see if restoring the old logic (which uses a separate API request to retrieve nameservers) is possible in newer module versions without affecting any existing functions.

**Comment by sapillai** [comment]
Hi @simonklink,

Thank you for waiting!

I have more information on this, the switch to function `GetDomainInformation` instead of `GetNameservers` was made based on the recommendation from WHMCS for version 7.6 and later. 
![image](https://github.com/user-attachments/assets/a5985037-2573-4726-8d1b-901066cb5ca8)
You can find this information in WHMCS [Function Index](https://developers.whmcs.com/domain-registrars/function-index/).

However, to help you with this, we have created a new [NameserverController.php](https://raw.githubusercontent.com/openprovider/Openprovider-WHMCS-domains/7cde726a8308413bf2fc36daf065e4694372a021/modules/registrars/openprovider/Controllers/System/NameserverController.php) with the old `getNameservers` function. You can download the file from the [link](https://raw.githubusercontent.com/openprovider/Openprovider-WHMCS-domains/7cde726a8308413bf2fc36daf065e4694372a021/modules/registrars/openprovider/Controllers/System/NameserverController.php) and replace your '**modules/registrars/openprovider/Controllers/System/NameserverController.php**' file with it.

Note: We won't be merging this change to master branch as WHMCS recommends using function `GetDomainInformation` for  WHMCS 7.6 and later.

**Comment by simonklink** [comment]
Hi @sapillai,

Thank you for the update! 
We will use the custom `NameserverController` class for now and switch to `GetDomainInformation` call on a later occasion.
