### ISSUE TITLE
[FR] Add support for domain forwarding

### ISSUE THREAD

**Issue by DAThosting** [openprovider/Openprovider-WHMCS-domains#68]
FEATURE REQUEST:

Add a option to enable domain forwarding for a domain and targetdomain.

**Comment by sapillai** [comment]
Hi @DAThosting, 

Thank you for submitting the feature request!

Currently, there isn't an API end-point available to activate the domain forwarding service. As a result, we are unable to incorporate this feature into the WHMCS module since it relies on API integration. However, I am adding this feature request to our list and we will consider adding it to WHMCS when it is possible to manage domain forwarding via API.
